### ISSUE TITLE
Erro when use svg2png in docker container

### ISSUE THREAD

**Issue by renanrboliveira** [domenic/svg2png#102]
Hi guys, when use this api in docker container the error below occurred:

> TypeError: Cannot read property 'toString' of null
    at processResult (/usr/src/mathjax-api/node_modules/svg2png/lib/svg2png.js:58:34)
    at Function.module.exports.sync (/usr/src/mathjax-api/node_modules/svg2png/lib/svg2png.js:25:12)
    at convert (/usr/src/mathjax-api/node_modules/mathjax-node-svg2png/lib/main.js:61:32)
    at /usr/src/mathjax-api/node_modules/mathjax-node-svg2png/lib/main.js:51:23
    at ReturnResult (/usr/src/mathjax-api/node_modules/mathjax-node/lib/main.js:785:3)
    at Function.execute (file:///usr/src/mathjax-api/node_modules/mathjax/unpacked/MathJax.js:243:26)
    at cb (file:///usr/src/mathjax-api/node_modules/mathjax/unpacked/MathJax.js:225:59)
    at Object.Process (file:///usr/src/mathjax-api/node_modules/mathjax/unpacked/MathJax.js:495:38)
    at Object.Push (file:///usr/src/mathjax-api/node_modules/mathjax/unpacked/MathJax.js:485:49)
    at Object.Queue (file:///usr/src/mathjax-api/node_modules/mathjax/unpacked/MathJax.js:2061:28)

But local that's ok, I don't know what's happening.

**Comment by CollegeFellow** [comment]
+1 Facing the same issue. Works fine on local but throwing error inside docker container.
```
TypeError: Cannot read property 'toString' of null
    at processResult (/home/code/node_modules/svg2png/lib/svg2png.js:58:34)
    at Function.module.exports.sync (/home/code/node_modules/svg2png/lib/svg2png.js:25:12)
    at getSeatLayout (/home/code/movies-app/lib/create-svg-seat-layout.js:236:34)
    at <anonymous>
```
Node Version `v8.9.1`
NPM Version `5.5.1`

**Comment by kabalage** [comment]
Have you guys solved this issue? I'm experiencing the same thing.

**Comment by kornsn** [comment]
@renanrboliveira So, how did you solve it???

**Comment by renanrboliveira** [comment]
Hi @kornsn, I didn’t.

**Comment by renanrboliveira** [comment]
I closed because I only use svg.

**Comment by JigSawFr** [comment]
Same problem on my side ...
