### ISSUE TITLE
sgv2png failing to work after macOS High Sierra upgrade

### ISSUE THREAD

**Issue by simonbm** [domenic/svg2png#105]
sgv2png failing to work after macOS High Sierra upgrade

Node JS v8.9.0
NPM 5.5.1

/usr/local/lib/node_modules/svg2png/lib/svg2png.js:58
    const stdout = result.stdout.toString();
                                 ^
TypeError: Cannot read property 'toString' of null
    at processResult (/usr/local/lib/node_modules/svg2png/lib/svg2png.js:58:34)
    at Function.module.exports.sync (/usr/local/lib/node_modules/svg2png/lib/svg2png.js:25:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/svg2png/bin/svg2png-cli.js:35:24)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)

**Comment by Tom32i** [comment]
Same here with node `v8.1.4` on High Sierra `10.13.1`.
Seems to be a problem with the `sync` method?

**Comment by mathieugerard** [comment]
I solved the problem by deleting all node_module and doing a fresh npm install. I expect phantomJS to build slightly differently on High Sierra. So there should be nothing to change on svg2png. Hope this helps.
