### ISSUE TITLE
Use of const in strict mode

### ISSUE THREAD

**Issue by iDVB** [domenic/svg2png#74]
Not sure if this is an issue with build settings or the svg2png itself, but when we build with node 0.12.0 it errors out... "[Use of const in strict mode.](http://stackoverflow.com/questions/22603078/syntaxerror-use-of-const-in-strict-mode)"

```
favicons-webpack-plugin\node_modules\favicons\node_modules\svg2png\lib\svg2png.js:2
const path = require("path");
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\www\klick-klickcom-2016-dev\node_modules\favicons-webpack-plugin\node_modules\favicons\helpers-es5.js:18:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\www\klick-klickcom-2016-dev\node_modules\favicons-webpack-plugin\node_modules\favicons\es5.js:11:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\www\klick-klickcom-2016-dev\node_modules\favicons-webpack-plugin\lib\favicons.js:3:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by domenic** [comment]
Please see the readme: https://github.com/domenic/svg2png#nodejs-requirements
