### ISSUE TITLE
PhantomJS crashes on this SVG

### ISSUE THREAD

**Issue by kasbah** [domenic/svg2png#77]
svg2png 4.1.1 and phantomjs 2.1.1 

![atari.svg](https://kaspar.h1x.com/atari.svg)

```
svg2png atari.svg
```
```
./node_modules/svg2png/lib/svg2png.js:65
        throw new Error(stdout.replace(/\r/g, "").trim());
        ^

Error: Width or height could not be determined from either the source file or the supplied dimensions

  phantomjs://code/converter.js:49 in onLoadFinished
    at processResult (./node_modules/svg2png/lib/svg2png.js:65:15)
    at Function.module.exports.sync (./node_modules/svg2png/lib/svg2png.js:25:12)
    at Object.<anonymous> (./node_modules/svg2png/bin/svg2png-cli.js:35:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
```

and 

```
svg2png atari.svg -w 240
```
```
./node_modules/svg2png/lib/svg2png.js:71
        throw new Error(stderr.replace(/\r/g, "").trim());
        ^

Error: PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
    at processResult (./node_modules/svg2png/lib/svg2png.js:71:15)
    at Function.module.exports.sync (./node_modules/svg2png/lib/svg2png.js:25:12)
    at Object.<anonymous> (./node_modules/svg2png/bin/svg2png-cli.js:35:24)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
```

**Comment by domenic** [comment]
Did you

> Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.

?

**Comment by kasbah** [comment]
No not yet, I am trying to figure out what's going wrong and if converter.js isn't at fault. 

EDIT: Actually, I'll try and get a stacktrace now like they suggest.

EDIT2: I couldn't get a stack trace yet (I don't know where the dumpfile is going, if there is one) but I traced it down to the `page.renderBase64("PNG")` call causing the crash. 

EDIT3: Looks like it's reported and downgrade to 2.0.0 is a workaround: https://github.com/ariya/phantomjs/issues/14248

**Comment by kasbah** [comment]
Actually, I'll try and get a stacktrace now.

**Comment by kasbah** [comment]
I couldn't get a stack trace yet (I don't know where the dumpfile is going, if there is one) but i traced it down to the `page.renderBase64("PNG")` call causing the crash.

**Comment by kasbah** [comment]
Looks like it's reported and downgrade to 2.0.0 is a workaround: https://github.com/ariya/phantomjs/issues/14248

**Comment by domenic** [comment]
Ah cool, OK, so we should probably do that in svg2png

**Comment by kasbah** [comment]
Beta of PhantomJS 2.5 was just released so that might solve it. https://groups.google.com/forum/#!topic/phantomjs/AefOuwkgBh0
