### ISSUE TITLE
throw new TypeError('"file" argument must be a non-empty string');

### ISSUE THREAD

**Issue by xiekunwhy** [domenic/svg2png#97]
Hi, I got these error warnings, and what's wrong? I can not find 'file' argument any where.
svg2png NB_final_snp_sub57.admixture.svg 
child_process.js:381
    throw new TypeError('"file" argument must be a non-empty string');
TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:381:11)
    at Object.spawnSync (child_process.js:510:38)
    at Function.module.exports.sync (/usr/local/lib/node_modules/svg2png/lib/svg2png.js:22:33)
    at Object.<anonymous> (/usr/local/lib/node_modules/svg2png/bin/svg2png-cli.js:35:24)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)

**Comment by danielnjoo** [comment]
I get the same error when running :

```
const svg2png = require("svg2png");
svg2png('foo.svg')
    .then(buffer => fs.writeFile("dest.png", buffer))
    .catch(e => console.error(e));
```

**Comment by gaurgs** [comment]
Any updates on this??

**Comment by domenic** [comment]
svg2png accepts a buffer, not a string.

**Comment by flaviotordini** [comment]
I'm having the same error running from command line:

`svg2png "material-design-icons-3.0.1/action/svg/production/ic_group_work_48px.svg" -o ciao.png -h 32
child_process.js:381
    throw new TypeError('"file" argument must be a non-empty string');
    ^

TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:381:11)
    at Object.spawnSync (child_process.js:517:38)
    at Function.module.exports.sync (/usr/lib/node_modules/svg2png/lib/svg2png.js:22:33)
    at Object.<anonymous> (/usr/lib/node_modules/svg2png/bin/svg2png-cli.js:35:24)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)`

**Comment by sorry510** [comment]
Maybe your phantomjs no installation is successful
